name: Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/python/requirements.txt
          mkdir $GITHUB_WORKSPACE/.npm-global
          npm config set prefix "$GITHUB_WORKSPACE/.npm-global"
          npm install -g jsdoc
          echo "$GITHUB_WORKSPACE/.npm-global/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          pip install -r docs/requirements.txt

      - name: Build
        run: make

      - name: Test
        run: make test
      - name: Docs
        working-directory: docs
        run: make
